#!/usr/bin/env python3
"""
5ノードオーケストレーター簡単テスト

基本的な調査タスクで応答生成ノードが正しく動作するかを確認
"""

import sys
import os
from pathlib import Path

# プロジェクトルートをパスに追加
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

try:
    from codecrafter.orchestration.five_node_orchestrator import FiveNodeOrchestrator
    from codecrafter.state.agent_state import AgentState
    from codecrafter.ui.rich_ui import rich_ui
    from codecrafter.base.config import config_manager
    import uuid
except ImportError as e:
    print(f"インポートエラー: {e}")
    print("プロジェクトルートから実行してください")
    sys.exit(1)


def test_simple_investigation():
    """簡単な調査タスクのテスト"""
    print("=== 5ノード調査タスクテスト ===")
    
    try:
        # AgentState初期化
        state = AgentState(
            session_id=str(uuid.uuid4()),
            debug_mode=True
        )
        
        # 5ノードオーケストレーター初期化
        orchestrator = FiveNodeOrchestrator(state)
        print("✅ 5ノードオーケストレーター初期化成功")
        
        # 調査タスクを実行
        test_message = "design-doc.mdの内容について教えて"
        print(f"テストメッセージ: {test_message}")
        
        # 対話実行
        orchestrator.run_conversation(test_message)
        
        # 結果確認
        print(f"\n=== 実行結果 ===")
        print(f"対話履歴数: {len(state.conversation_history)}")
        
        # 各メッセージを確認
        for i, msg in enumerate(state.conversation_history):
            print(f"{i+1}. {msg.role}: {len(msg.content)}文字")
            if msg.role == 'assistant':
                print(f"   内容プレビュー: {msg.content[:200]}...")
                
                # 応答生成ノードが動作したかを確認
                if "Generated by Duckflow" in msg.content:
                    print("✅ 応答生成ノードが動作しました")
                    return True
                elif len(msg.content) > 500:
                    print("✅ 詳細な応答が生成されました")
                    return True
                else:
                    print("⚠️ 短い応答です - 応答生成ノードが動作していない可能性")
        
        return len(state.conversation_history) > 1
        
    except Exception as e:
        print(f"❌ テスト失敗: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    """メインテスト実行"""
    print("5ノード調査タスクテストを開始します\n")
    
    success = test_simple_investigation()
    
    if success:
        print("\n🎉 テスト成功！")
        print("5ノードオーケストレーターは基本的に動作しています。")
    else:
        print("\n❌ テスト失敗")
        print("問題を確認してください。")
    
    return success


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)