#!/usr/bin/env python3
"""
test_step2d_graph.pyファイル探索・分析シナリオテスト

実際のユーザーシナリオ「test_step2d_graph.pyファイルを探して処理内容を説明してください」
を5ノードオーケストレーターで実行し、動作を確認する
"""

import sys
import os
from pathlib import Path

# プロジェクトルートをパスに追加
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

try:
    from codecrafter.main_v2 import DuckflowAgentV2
    from codecrafter.orchestration.five_node_orchestrator import FiveNodeOrchestrator
    import uuid
except ImportError as e:
    print(f"インポートエラー: {e}")
    print("プロジェクトルートから実行してください")
    sys.exit(1)


def test_step2d_graph_scenario():
    """test_step2d_graph.pyファイル探索・分析シナリオ"""
    print("=== test_step2d_graph.py 探索・分析シナリオテスト ===")
    
    try:
        # DuckflowAgentV2初期化
        agent = DuckflowAgentV2()
        print("✅ DuckflowAgentV2初期化成功")
        
        # 実際のユーザーシナリオメッセージ
        user_message = "test_step2d_graph.pyファイルを探して処理内容を説明してください"
        print(f"\n📝 ユーザーメッセージ: {user_message}")
        
        print("\n" + "="*60)
        print("🚀 5ノードオーケストレーション実行開始")
        print("="*60)
        
        # 対話実行
        agent._handle_orchestrated_conversation(user_message)
        
        print("\n" + "="*60)
        print("📊 実行結果分析")
        print("="*60)
        
        # 結果確認
        if agent.state.conversation_history:
            print(f"✅ 対話履歴数: {len(agent.state.conversation_history)}メッセージ")
            
            # 各メッセージの詳細を表示
            for i, msg in enumerate(agent.state.conversation_history):
                print(f"\n{i+1}. {msg.role.upper()}: {len(msg.content)}文字")
                if msg.role == 'user':
                    print(f"   内容: {msg.content}")
                elif msg.role == 'assistant':
                    # アシスタント応答の分析
                    content = msg.content
                    
                    # 応答の特徴を分析
                    analysis = {
                        "ファイル発見": "test_step2d_graph" in content.lower(),
                        "処理内容説明": any(keyword in content for keyword in ["def ", "class ", "import ", "関数", "クラス"]),
                        "コード内容": "```" in content,
                        "構造化レポート": "##" in content and "###" in content,
                        "詳細分析": len(content) > 2000,
                        "TaskProfile使用": "Generated by Duckflow" in content
                    }
                    
                    print(f"   📋 応答分析:")
                    for feature, detected in analysis.items():
                        status = "✅" if detected else "❌"
                        print(f"      {status} {feature}: {detected}")
                    
                    # 応答内容のプレビュー
                    print(f"\n   📄 応答プレビュー:")
                    print("   " + "-" * 50)
                    preview = content[:500].replace('\n', '\n   ')
                    print(f"   {preview}")
                    if len(content) > 500:
                        print(f"   ... [残り{len(content) - 500}文字]")
                    print("   " + "-" * 50)
                    
                    # 成功判定
                    success_criteria = [
                        analysis["ファイル発見"],
                        analysis["処理内容説明"],
                        analysis["構造化レポート"],
                        len(content) > 1000
                    ]
                    
                    success_rate = sum(success_criteria) / len(success_criteria)
                    
                    if success_rate >= 0.75:
                        print(f"\n   🎉 シナリオ成功率: {success_rate:.1%} - 優秀")
                        return True
                    elif success_rate >= 0.5:
                        print(f"\n   ⚠️ シナリオ成功率: {success_rate:.1%} - 部分的成功")
                        return True
                    else:
                        print(f"\n   ❌ シナリオ成功率: {success_rate:.1%} - 改善が必要")
                        return False
        else:
            print("❌ 対話履歴が空です")
            return False
        
        return True
        
    except Exception as e:
        print(f"❌ シナリオテスト失敗: {e}")
        import traceback
        traceback.print_exc()
        return False


def analyze_orchestration_flow():
    """オーケストレーションフローの分析"""
    print("\n" + "="*60)
    print("🔍 5ノードオーケストレーションフロー分析")
    print("="*60)
    
    expected_flow = [
        "1️⃣ [The Architect] 理解・計画フェーズ",
        "   - ファイル名抽出: test_step2d_graph.py",
        "   - TaskProfile分類: file_analysis",
        "   - needs_file_read: True",
        "",
        "2️⃣ [The Librarian] 情報収集フェーズ",
        "   - Duck Scan実行: test_step2d_graph検索",
        "   - ファイル読み取り: 実際のコード取得",
        "   - FileContent変換: 分析用データ構造",
        "",
        "3️⃣ [Quality Gate & Controller] 評価・継続フェーズ",
        "   - 収集情報の品質評価",
        "   - 次のアクション決定: response_generation",
        "",
        "4️⃣ [The Scribe] 応答生成フェーズ",
        "   - TaskProfileテンプレート使用",
        "   - ファイル内容の詳細分析",
        "   - 構造化レポート生成"
    ]
    
    print("期待されるフロー:")
    for step in expected_flow:
        print(step)
    
    print("\n✅ このフローにより、以下が実現されます:")
    print("   - 正確なファイル特定・取得")
    print("   - 実際のコード内容分析")
    print("   - 構造化された詳細レポート")
    print("   - 決定論的で予測可能な応答品質")


def main():
    """メインテスト実行"""
    print("🦆 Duckflow 5ノードアーキテクチャ")
    print("test_step2d_graph.py 探索・分析シナリオテスト")
    print("="*60)
    
    # フロー分析を先に表示
    analyze_orchestration_flow()
    
    # 実際のシナリオテスト実行
    success = test_step2d_graph_scenario()
    
    print("\n" + "="*60)
    print("🏁 最終結果")
    print("="*60)
    
    if success:
        print("🎉 シナリオテスト成功！")
        print("✅ 5ノードオーケストレーターは期待通りに動作しています")
        print("✅ test_step2d_graph.pyファイルの探索・分析が正常に実行されました")
        print("✅ 構造化された詳細レポートが生成されました")
    else:
        print("❌ シナリオテスト失敗")
        print("⚠️ 問題を確認して修正してください")
    
    return success


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)